name: ISI-Burger

# Déclenche la pipeline sur un push vers la branche 'main'
on:
  push:
    branches:
      - main

# Définition des jobs
jobs:
  # Job pour tester le projet
  tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code de la branche
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Ajustez selon la version de PHP requise par votre projet

      # Étape 3 : Installer les dépendances Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: vendor/bin/phpunit

  # Job pour construire l'image Docker
  build:
    # Ce job ne s'exécute que si le job 'tests' réussit
    needs: tests
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code de la branche
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t my-laravel-app .
